version: 0.2

env:
  variables:
    IMAGE_BASE_NAME: "swisstopo/service-alti"
    SHELL: "/bin/bash"
    AWS_DEFAULT_REGION: eu-central-1
    TEST_REPORT_DIR: "./tests/report"
    TEST_REPORT_FILE: "nose2-junit.xml"
    PIPENV_NOSPIN: 1
  parameter-store:
    CI_DOCKERHUB_USER: "/dockerhub/user"
    CI_DOCKERHUB_PASSWORD: "/dockerhub/password"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing necessary softwares"
      - docker login -u ${CI_DOCKERHUB_USER} -p ${CI_DOCKERHUB_PASSWORD}
      # - apt-get update && apt-get install -y docker-compose python3 python3-venv python3-pip

  pre_build:
    commands:
      - echo "Exporting of the image tag for building and pushing purposes"
      # Reading git branch (the utility in the deploy script is unable to read it automatically on CodeBuild)
      # see https://stackoverflow.com/questions/47657423/get-github-git-branch-for-aws-codebuild
      - export GITHUB_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - |
        if [ "${GITHUB_BRANCH}" = "" ] ; then
          GITHUB_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          export GITHUB_BRANCH=${GITHUB_BRANCH#remotes/origin/};
        fi
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "GITHUB_BRANCH=${GITHUB_BRANCH} COMMIT_HASH=${COMMIT_HASH}"
      - echo "creating a clean environment"
      - make ci
      - echo "check code formatting"
      - make ci-check-format
      - echo "linting code"
      - make lint

  build:
    commands:
      - echo Build started on $(date)
      - export DOCKER_IMG_TAG_BASE=${IMAGE_BASE_NAME}:${GITHUB_BRANCH}
      - export DOCKER_IMG_TAG_HASH_COMMIT=${DOCKER_IMG_TAG_BASE}.${COMMIT_HASH}
      - export DOCKER_IMG_TAG_LATEST=${DOCKER_IMG_TAG_BASE}.latest
      - echo "Building docker image with tags ${DOCKER_IMG_TAG_HASH_COMMIT} and ${DOCKER_IMG_TAG_LATEST}"
      - docker build -t ${DOCKER_IMG_TAG_HASH_COMMIT} -t ${DOCKER_IMG_TAG_LATEST} .

  post_build:
    commands:
      - make lint
      - mkdir -p ${TEST_REPORT_DIR}
      - export TEST_REPORT_DIR=${TEST_REPORT_DIR}
      - export TEST_REPORT_FILE=${TEST_REPORT_FILE}
      - make test
      # Only push image to dockerhub for merges on develop and master
      # by not specifying one of the two tagging above but the common part the two tags will be
      # pushed together (e.g. swisstopo/service-alti:develop.1234567 and swisstopo/service-alti:develop.latest
      # if we push swisstopo/service-alti:develop the two tags will be pushed together)
      - |
        if [ "${GITHUB_BRANCH}" = "master" -o "${GITHUB_BRANCH}" = "develop" ]; then
          docker push ${DOCKER_IMG_TAG_HASH_COMMIT}
          docker push ${DOCKER_IMG_TAG_LATEST}
        fi
      - echo Build completed on $(date)

reports:
  nose2_reports:
    files:
      - ${TEST_REPORT_FILE}
    base-directory: ${TEST_REPORT_DIR}
    file-format: JunitXml