version: "2"
services:
  app:
    image: swisstopo/service-alti:local
    environment:
      - DTM_BASE_PATH
      - LOGGING_CFG
      - LOGS_DIR=/logs
    ports:
      - "${HTTP_PORT}:8080"
    volumes:
      - "${LOGS_DIR}:/logs"
