name: Bump version
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: "10"
      # Details and Documentation
      # https://github.com/anothrNick/github-tag-action
      # https://github.com/geoadmin/doc-guidelines/blob/master/GIT_FLOW.md#versioning
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: master
          TAG_CONTEXT: repo